import { ColorScheme } from "@/hooks/useTheme";
import { StyleSheet } from "react-native";

export const createHomeStyles = (colors: ColorScheme) => {
  const styles = StyleSheet.create({
    safecontainer: {
      paddingHorizontal: 24,
      paddingTop: 40,
      flex: 1,
      backgroundColor: '#FAFAFA',
    },
    content: {
      paddingHorizontal: 5,
      paddingVertical: 20,
      gap: 20,
    },
    headerContainer: {
      marginBottom: 12,
    },
    helloView: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
    },
    waveHand: {
      width: 32,
      height: 32,
      marginRight: 8,
    },
    helloText: {
      fontSize: 18,
      fontWeight: '400',
      color: '#6B7280',
      letterSpacing: 0.3,
    },
    userName: {
      fontSize: 18,
      fontWeight: '600',
      color: '#D4A574',
      letterSpacing: 0.3,
    },
    welcomeView: {
      marginTop: 4,
    },
    welcomeText: {
      fontSize: 32,
      fontWeight: '700',
      color: '#1F2937',
      lineHeight: 40,
      letterSpacing: -0.5,
    },
    welcomeHighlight: {
      color: '#C9984E',
    },
    subtitleText: {
      fontSize: 15,
      fontWeight: '400',
      color: '#9CA3AF',
      marginTop: 8,
      letterSpacing: 0.2,
    },
    askCard: {
      paddingVertical: 30,
      paddingHorizontal: 24,
      borderRadius: 20,
      shadowColor: '#C9984E',
      shadowOffset: {
        width: 0,
        height: 8,
      },
      shadowOpacity: 0.25,
      shadowRadius: 12,
      elevation: 10,
    },
    askCardContent: {
      gap: 12,
    },
    askCardHead: {
      fontSize: 24,
      color: '#FFFFFF',
      fontWeight: '700',
      letterSpacing: -0.3,
      lineHeight: 30,
    },
    askCardDescription: {
      fontSize: 15,
      color: '#FFFFFF',
      opacity: 0.9,
      fontWeight: '400',
      letterSpacing: 0.2,
      marginBottom: 4,
    },
    askCardBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingHorizontal: 20,
      paddingVertical: 12,
      borderRadius: 12,
      backgroundColor: '#FFFFFF',
      marginTop: 8,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    askCardBtnText: {
      fontSize: 15,
      fontWeight: '600',
      color: '#C9984E',
      letterSpacing: 0.3,
    },
    askCardIcon: {
      marginLeft: 4,
    },
    pathSection: {
      marginTop: 24,
      gap: 12,
    },
    pathSectionTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: '#1F2937',
      marginBottom: 4,
      letterSpacing: -0.3,
    },
    pathGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
    },
    pathBtn: {
      flex: 1,
      minWidth: '47%',
      paddingHorizontal: 16,
      paddingVertical: 16,
      borderRadius: 16,
      backgroundColor: '#FFFFFF',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 3,
      borderWidth: 1,
      borderColor: '#F3F4F6',
    },
    pathBtnContent: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    pathBtnEmoji: {
      fontSize: 24,
    },
    pathBtnText: {
      fontSize: 14,
      fontWeight: '600',
      color: '#374151',
      letterSpacing: 0.2,
    },
    pathBtnSubtext: {
      fontSize: 12,
      fontWeight: '400',
      color: '#9CA3AF',
      marginTop: 4,
      letterSpacing: 0.1,
    },
    recentSection: {
      marginTop: 24,
    },
    recentSectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
    },
    recentSectionTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: '#1F2937',
      letterSpacing: -0.3,
    },
    recentSectionViewAll: {
      fontSize: 14,
      fontWeight: '600',
      color: '#C9984E',
    },
    recentCardsContainer: {
      gap: 10,
    },
    recentCard: {
      backgroundColor: '#FFFFFF',
      padding: 16,
      borderRadius: 14,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.05,
      shadowRadius: 6,
      elevation: 2,
      borderWidth: 1,
      borderColor: '#F3F4F6',
    },
    recentCardTop: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    recentCardLeft: {
      flex: 1,
      gap: 6,
    },
    recentCardCategory: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    recentCardCategoryBadge: {
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 6,
      backgroundColor: '#FEF3C7',
    },
    recentCardCategoryText: {
      fontSize: 11,
      fontWeight: '600',
      color: '#92400E',
    },
    recentCardTitle: {
      fontSize: 15,
      fontWeight: '600',
      color: '#1F2937',
      letterSpacing: -0.2,
      lineHeight: 20,
    },
    recentCardDescription: {
      fontSize: 13,
      fontWeight: '400',
      color: '#6B7280',
      letterSpacing: 0.1,
      lineHeight: 18,
      marginTop: 4,
    },
    recentCardTime: {
      fontSize: 11,
      fontWeight: '500',
      color: '#9CA3AF',
    },
    recentCardBottom: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: 10,
      paddingTop: 10,
      borderTopWidth: 1,
      borderTopColor: '#F3F4F6',
    },
    recentCardStats: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    recentCardStat: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    recentCardStatText: {
      fontSize: 12,
      fontWeight: '500',
      color: '#dc9a38ff',
    },
    recentCardArrow: {
      width: 28,
      height: 28,
      borderRadius: 8,
      backgroundColor: '#F9FAFB',
      alignItems: 'center',
      justifyContent: 'center',
    },
        statsSection: {
      marginTop: 24,
    },
    statsCard: {
      backgroundColor: '#FFFFFF',
      paddingHorizontal: 20,
      paddingVertical: 20,
      borderRadius: 16,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 2,
      borderWidth: 1,
      borderColor: '#F3F4F6',
      gap: 14,
    },
    statItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 2,
    },
    statLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    statEmoji: {
      fontSize: 22,
    },
    statLabel: {
      fontSize: 15,
      fontWeight: '500',
      color: '#4B5563',
      letterSpacing: 0.1,
    },
    statValue: {
      fontSize: 16,
      fontWeight: '700',
      color: '#1F2937',
      letterSpacing: -0.2,
    },
    statValueHighlight: {
      color: '#C9984E',
    },
    statDivider: {
      height: 1,
      backgroundColor: '#F3F4F6',
      marginVertical: 2,
    },
    statsSectionTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: '#1F2937',
      marginBottom: 12,
      letterSpacing: -0.3,
    },
  });
  return styles;
};